sonar.projectKey=KeaKit_KeaKit
sonar.organization=keakit-sonarqubeconfigkey
sonar.projectName=KeaKit

sonar.sources=backend/src, mobile/src
sonar.tests=backend/src/test, mobile/__tests__

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

sonar.javascript.lcov.reportPaths=mobile/coverage/lcov.info
