sonar.projectKey=KeaKit_KeaKit
sonar.organization=keakit-sonarqubeconfigkey
sonar.projectName=KeaKit

# Código y tests
sonar.sources=backend/src/main/java, mobile/src
sonar.tests=backend/src/test/java, mobile/__tests__

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

# Java: clases compiladas
sonar.java.binaries=backend/target/classes

# Cobertura backend (Jacoco)
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

# Cobertura frontend (Jest)
sonar.javascript.lcov.reportPaths=mobile/coverage/lcov.info
