sonar.projectKey=KeaKit_KeaKit
sonar.organization=keakit-sonarqubeconfigkey
sonar.projectName=KeaKit

# BACKEND
sonar.sources=backend/src/main/java
sonar.tests=backend/src/test/java

# FRONTEND
sonar.sources=backend/src/main/java, mobile/src
sonar.tests=backend/src/test/java, mobile/__tests__

# Exclusiones
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

# Cobertura backend (Jacoco)
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

# Cobertura frontend (Jest)
sonar.javascript.lcov.reportPaths=mobile/coverage/lcov.info
