SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE transactions;
TRUNCATE TABLE ratings;
TRUNCATE TABLE items;
TRUNCATE TABLE articles;
TRUNCATE TABLE kits;
TRUNCATE TABLE wallets;
TRUNCATE TABLE users;
TRUNCATE TABLE categories;

ALTER TABLE transactions ALTER COLUMN id RESTART WITH 1;
ALTER TABLE ratings ALTER COLUMN id RESTART WITH 1;
ALTER TABLE items ALTER COLUMN id RESTART WITH 1;
ALTER TABLE kits ALTER COLUMN id RESTART WITH 1;
ALTER TABLE wallets ALTER COLUMN id RESTART WITH 1;
ALTER TABLE users ALTER COLUMN id RESTART WITH 1;
ALTER TABLE articles ALTER COLUMN id RESTART WITH 1;
ALTER TABLE categories ALTER COLUMN id RESTART WITH 1;

SET REFERENTIAL_INTEGRITY TRUE;