spring:
  application:
    name: demo
  
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres-1:5432/appdb}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # --- CONFIGURACIÓN PARA QUE CONVIVAN ---
  sql:
    init:
      mode: always # Asegura que data.sql se intente ejecutar siempre

  jpa:
    defer-datasource-initialization: true # Obliga a data.sql a esperar a Hibernate
    hibernate:
      ddl-auto: create 
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:KeaKitSecureSecretKey12345678901234567890ABCDEFGHIJKLMNOP}
  expiration: 86400000 

app:
  setup:
    admin:
      email: ${ADMIN_EMAIL:admin@example.com}
      password: ${ADMIN_PASSWORD:admin123}
      name: ${ADMIN_NAME:Admin Initial}