name: CD - Deploy Frontend to Firebase

on:
  workflow_run:
    workflows: ["Frontend CI"]
    types:
      - completed
    branches:
      - main
      - 'release/*.*.*'
      - fix/SEO-robots

jobs:
  deploy-frontend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mobile

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configurar Node.js v24.13.1
        uses: actions/setup-node@v4
        with:
          node-version: '24.13.1'
          cache: 'npm'
          cache-dependency-path: mobile/package-lock.json

      - name: Instalar dependencias
        run: npm ci

      - name: Crear archivo .env de Expo
        env:
          MOBILE_ENV: ${{ secrets.MOBILE_ENV_FILE }}
        run: echo "$MOBILE_ENV" > .env

      - name: Construir la web con Expo
        run: npx expo export --platform web

      - name: Desplegar a Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PPL }}'
          projectId: '${{ secrets.FIREBASE_PROJECT_ID_PPL }}'
          channelId: 'live' 
          # Esto le dice a Firebase que el comando se ejecuta desde la carpeta mobile
          entryPoint: mobile