name: Actualizar Fechas en Proyecto

on:
  issues:
    types: [edited]
  pull_request:
    types: [edited]

jobs:
  actualizar-fecha-segun-estado:
    runs-on: ubuntu-latest
    # if: github.event.changes && github.event.issue
    
    steps:
      - name: Obtener fecha actual
        id: current-date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Establecer fecha en TODO At
        uses: nipe0324/update-project-v2-item-field@v1.0
        if: github.event.changes.issue.field_value.to.name == 'TODO'
        with:
          project-url: 'https://github.com/orgs/KeaKit/projects/2'
          github-token: ${{ secrets.GH_TOKEN }}
          field-name: 'TODO At'
          field-value: ${{ steps.current-date.outputs.date }}

      - name: Establecer fecha en In Progress At
        uses: nipe0324/update-project-v2-item-field@v1.0
        if: github.event.changes.issue.field_value.to.name == 'In Progress'
        with:
          project-url: 'https://github.com/orgs/KeaKit/projects/2'
          github-token: ${{ secrets.GH_TOKEN }}
          field-name: 'In Progress At'
          field-value: ${{ steps.current-date.outputs.date }}

      - name: Establecer fecha en In Review At
        uses: nipe0324/update-project-v2-item-field@v1.0
        if: github.event.changes.issue.field_value.to.name == 'In Review'
        with:
          project-url: 'https://github.com/orgs/KeaKit/projects/2'
          github-token: ${{ secrets.GH_TOKEN }}
          field-name: 'In Review At'
          field-value: ${{ steps.current-date.outputs.date }}

      - name: Establecer fecha en Done At
        uses: nipe0324/update-project-v2-item-field@v1.0
        if: github.event.changes.issue.field_value.to.name == 'Done'
        with:
          project-url: 'https://github.com/orgs/KeaKit/projects/2'
          github-token: ${{ secrets.GH_TOKEN }}
          field-name: 'Done At'
          field-value: ${{ steps.current-date.outputs.date }}